const AUDIT_ACTION_LABELS: Record<string, string> = {
  USER_LOGIN: "Connexion réussie",
  USER_LOGIN_2FA: "Connexion 2FA réussie",
  USER_LOGOUT: "Déconnexion",
  LOGIN_FAILED: "Échec de connexion",
  SECURITY_ALERT: "Alerte sécurité",
  USER_CREATED: "Utilisateur créé",
  USER_UPDATED: "Utilisateur modifié",
  USER_BLOCKED: "Utilisateur bloqué",
  USER_ACTIVATED: "Utilisateur activé",
  ROLE_PERMISSION_GRANTED: "Permission accordée au rôle",
  ROLE_PERMISSION_REVOKED: "Permission retirée du rôle",
  ROLE_PERMISSIONS_UPDATED: "Permissions rôle modifiées",
  PASSWORD_CHANGED: "Mot de passe modifié",
  SESSION_REVOKED: "Session révoquée",
  TWO_FACTOR_ENABLED: "2FA activée",
  TWO_FACTOR_DISABLED: "2FA désactivée",
  CLIENT_CREATED: "Client créé",
  CLIENT_UPDATED: "Client modifié",
  CLIENT_IMPORTED: "Client importé (CSV)",
  CLIENT_ARCHIVED: "Client archivé",
  CLIENT_RESTORED: "Client restauré",
  CLIENT_TAG_ADDED: "Tag client ajouté",
  CLIENT_TAG_REMOVED: "Tag client retiré",
  CLIENT_NOTE_CREATED: "Note client ajoutée",
  REVENUE_CREATED: "Revenu enregistré",
  REVENUE_PAYMENT_RECORDED: "Encaissement enregistré",
  RECEIVABLE_REMINDER_SENT: "Rappel de créance envoyé",
  REVENUE_CANCELLED: "Revenu annulé",
  EXPENSE_CREATED: "Dépense enregistrée",
  EXPENSE_APPROVED: "Dépense approuvée",
  EXPENSE_REJECTED: "Dépense refusée",
  EXPENSE_ADJUSTMENT_CREATED: "Avoir / régularisation",
  EXPENSE_ATTACHMENT_ADDED: "Pièce jointe ajoutée",
  TRANSACTION_ADJUSTMENT_CREATED: "Avoir / régularisation créé",
  CASH_ADVANCE_REQUESTED: "Avance de caisse demandée",
  CASH_ADVANCE_APPROVED: "Avance de caisse approuvée",
  CASH_ADVANCE_REJECTED: "Avance de caisse refusée",
  CASH_ADVANCE_DISBURSED: "Avance de caisse décaissée",
  RECURRING_EXPENSE_CREATED: "Dépense récurrente créée",
  RECURRING_EXPENSE_TEMPLATE_CREATED: "Modèle de dépense récurrente créé",
  RECURRING_EXPENSE_DISBURSED: "Dépense récurrente décaissée",
  RECURRING_EXPENSE_DUE_GENERATED: "Échéance récurrente générée",
  REVENUE_REALIZED: "Prestation marquée comme réalisée",
  EXPENSE_APPROVAL_REQUESTED: "Approbation de dépense demandée",
  EXPENSE_ATTACHMENT_UPLOADED: "Pièce jointe téléversée",
  SESSIONS_REVOKED_OTHERS: "Autres sessions révoquées",
  CLIENT_NOTE_ADDED: "Note client ajoutée",
  USER_SEEDED: "Compte initial créé",
  PASSWORD_RESET_REQUESTED: "Réinitialisation de mot de passe demandée",
  PASSWORD_RESET_COMPLETED: "Mot de passe réinitialisé",
  PASSWORD_ADMIN_RESET: "Mot de passe réinitialisé (admin)",
  CASH_CLOSING_CREATED: "Clôture de caisse",
  CASH_CLOSING_REVIEW_APPROVED: "Clôture validée (PDG)",
  CASH_CLOSING_REVIEW_RESOLVED: "Clôture régularisée (PDG)",
  FISCAL_PERIOD_INITIALIZED: "Trimestre comptable initialisé",
  FISCAL_PERIOD_CLOSING_REQUESTED: "Clôture trimestrielle demandée",
  FISCAL_PERIOD_CLOSING_ACCOUNTANT_APPROVED: "Visa comptable — clôture trimestrielle",
  FISCAL_PERIOD_CLOSING_APPROVED: "Clôture trimestrielle validée",
  FISCAL_PERIOD_CLOSED: "Trimestre comptable clôturé",
  FISCAL_PERIOD_OPENED: "Trimestre comptable ouvert",
  FINANCIAL_REGISTER_EXPORTED: "Export registre comptable",
  FINANCIAL_PERIOD_CLOSED: "Clôture mensuelle — bilan périodique",
  CRITICAL_ALERT_DISPATCHED: "Alerte critique envoyée",
  ALERT_SETTINGS_UPDATED: "Configuration alertes modifiée",
  ALERT_INTEGRATION_PING_SENT: "Ping test alertes envoyé",
  AUDIT_LOG_EXPORTED: "Export des journaux d'audit",
};

const AUDIT_ENTITY_LABELS: Record<string, string> = {
  User: "Utilisateur",
  Client: "Client",
  Transaction: "Revenu ou dépense",
  CashClosing: "Clôture de caisse",
  FiscalPeriod: "Trimestre comptable",
  FinancialPeriodClosure: "Clôture mensuelle",
  Role: "Rôle",
  AuditLog: "Journal d'audit",
  UserSession: "Session",
};

export function getAuditActionLabel(action: string): string {
  return AUDIT_ACTION_LABELS[action] ?? action.replaceAll("_", " ").toLowerCase();
}

export function getAuditEntityLabel(entity: string): string {
  return AUDIT_ENTITY_LABELS[entity] ?? entity;
}

export const AUDIT_ACTION_OPTIONS = Object.entries(AUDIT_ACTION_LABELS).map(([value, label]) => ({
  value,
  label,
}));
